### ISSUE TITLE
[BUG] Date of vaccination seems to be missing in the Pass

### ISSUE THREAD

**Issue by vmax77** [clawfire/covid19-passbook-generator#287] opened 2021-10-19 05:30 UTC
### Contact Details

vignesh.v711@gmail.com

### What happened?

Hi! Excellent work on the pass generation. Whn I get more info, the date of Vaccination field seems to be empty. Also it would be really nice, if the date of the latest dose to be displayed on the main wallet. 

Thank you

### What browsers are you seeing the problem on?

Chrome, Safari

### Are you browsing using

an iPhone

### Anything else?

![IMG_1587](https://user-images.githubusercontent.com/4384278/137849297-a5677a15-99e6-4264-a4ac-91769cf34483.PNG)

**Comment by clawfire** [comment] 2021-11-01 16:09
I gonna close this one as duplicate of #281, a fix is on its way thanks to @biou

**Closed by clawfire** 2021-11-01 16:09 UTC
Labels: bug, no-issue-activity
