### ISSUE TITLE
[BUG] Can't download the file on webview

### ISSUE THREAD

**Issue by mslawomir** [clawfire/covid19-passbook-generator#33] opened 2021-07-02 08:31 UTC
**Describe the bug**
the code is scanned but can’t save (download) the file to save it in my wallet 

**To Reproduce**
1. scan code 
2. Click on “save button”

*expected*
saved file with code
 
 

**Smartphone (please complete the following information):**
 - Device: [e.g. iPhone7
 - OS: [e.g. iOS 14.1

**Additional context**

**Comment by grischard** [comment] 2021-07-02 08:50
Welcome @mslawomir, thank you for opening your first issue.

Just to confirm: the QR code gets shown correctly on the screen, but the save button doesn't work?

You are looking at the page in the Safari app, not the web page view in Facebook, Twitter or something similar?

What country is your certificate from?

**Comment by mslawomir** [comment] 2021-07-02 09:13
Hi,


the QR code gets shown correctly on the screen, but the save button doesn't work?  - yes


You are looking at the page in the Safari app, not the web page view in Facebook, Twitter or something on Facebook

What country is your certificate from? - Luxembourg

Best regards,

Sławomir

Wiadomość napisana przez Guillaume Rischard ***@***.***> w dniu 2/07/2021, o godz. 10:50:

﻿

Welcome @mslawomir<https://github.com/mslawomir>, thank you for opening your first issue.

Just to confirm: the QR code gets shown correctly on the screen, but the save button doesn't work?

You are looking at the page in the Safari app, not the web page view in Facebook, Twitter or something

What country is your certificate from?

**Comment by grischard** [comment] 2021-07-02 10:47
Hi Sławomir,

It's probably because Apple doesn't allow Facebook to add stuff to the Wallet app. Can you try reproducing the bug in Safari?

Related bug: #25

**Comment by mslawomir** [comment] 2021-07-02 10:54
No - in safari it’s fine

Best regards,

Sławomir

Wiadomość napisana przez Guillaume Rischard ***@***.***> w dniu 2/07/2021, o godz. 12:47:

﻿

Hi Sławomir,

It's probably because Apple doesn't allow Facebook to add stuff to the Wallet app. Can you try reproducing the bug in Safari?

Related bug: #25<https://github.com/clawfire/covid19-passbook-generator/issues/25>

**Comment by grischard** [comment] 2021-07-02 10:54
Thank you!

**Comment by clawfire** [comment] 2021-07-02 15:05
I think it's related to #25 and will be fixed with it.

**Closed** 2021-07-14 09:02 UTC
Labels: bug, bug:wallet, invalid, wontfix
